version: '3.8'

services:
  # MySQL 数据库
  mysql:
    image: mysql:8.0
    container_name: ordering-mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ordering_system
      MYSQL_USER: ordering_user
      MYSQL_PASSWORD: ordering_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ordering-network-dev

  # Redis 缓存
  redis:
    image: redis:6.2-alpine
    container_name: ordering-redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    networks:
      - ordering-network-dev

volumes:
  mysql_data_dev:
  redis_data_dev:

networks:
  ordering-network-dev:
    driver: bridge 