server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ordering-system
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ordering_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterSetResults=utf8&connectionCollation=utf8_general_ci
    username: root
    password: 12345678
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        connection:
          characterEncoding: utf8
          useUnicode: true
          charSet: utf8
        

        
  # Redis配置
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
        
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT配置
jwt:
  secret: ordering-system-jwt-secret-key-2024-very-long-secret-key-for-hs512-algorithm
  expiration: 86400000  # 24小时
  header: Authorization
  prefix: Bearer

# 微信小程序配置
wechat:
  appid: wxd6f16a58b090692e
  secret: 9a5cf664f0f384a69f437213a2e8b464
  miniprogram:
    appid: wxd6f16a58b090692e  # 替换为你的小程序AppID
    secret: 9a5cf664f0f384a69f437213a2e8b464  # 替换为你的小程序AppSecret
  
# 阿里云OSS配置
aliyun:
  oss:
    endpoint: your-oss-endpoint
    access-key-id: your-access-key-id
    access-key-secret: your-access-key-secret
    bucket-name: your-bucket-name



# 日志配置
logging:
  level:
    com.myster.demo: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/ordering-system.log

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 